#This container is only for dev purposes
version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ddrpc
      POSTGRES_USER: ddrpcdev
      POSTGRES_PASSWORD: ddrpc123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
volumes:
  postgres_data:
