ALTER TABLE RpcPlans DROP COLUMN created;
ALTER TABLE RpcPlans ADD COLUMN created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE RpcPlans DROP COLUMN expires;
ALTER TABLE RpcPlans ADD COLUMN expires TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP + INTERVAL '1 months';

ALTER TABLE Customers DROP COLUMN created;
ALTER TABLE Customers ADD COLUMN created TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE Payments DROP COLUMN date;
ALTER TABLE Payments ADD COLUMN date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP; 
