name: docker-build-test

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      -
        name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
    #   -
    #     name: Build and export 
    #     uses: docker/build-push-action@v6
    #     with:
    #       push: false
    #       load: true
    #       tags: Developer-DAO/rpc:latest

    #   - 
    #     name: Test the container
    #     run: docker run -p 3000:3000 Developer-DAO/rpc:latest

      -
        name: Build and push 
        uses: docker/build-push-action@v6
        with:
          push: true
          load: false
          tags: ghcr.io/developer-dao/rpc:latest