name: Terraform ECS Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [docker-image-pushed]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/opentofu/ecs
    env:
      AWS_REGION: us-east-2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="rpc_image=${{ github.event.client_payload.image_tag }}"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="rpc_image=${{ github.event.client_payload.image_tag }}"
